[package]
name = "bao-core"
version = "0.1.0"
edition = "2021"
authors = ["Skye", "Dean Srebnik"]

[lib]
path = "lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
